from environs import Env

env = Env()
env.read_env()


class Config:
    RABBITMQ_URI = env("RABBITMQ_URI")
    USERS_TO_CREATE_QUEUE = env("USERS_TO_CREATE_QUEUE")
    USERS_TO_DELETE_QUEUE = env("USERS_TO_DELETE_QUEUE")
    BOARDS_TO_RENDER_QUEUE = env("BOARDS_TO_RENDER_QUEUE")
    RENDERED_BOARDS_EXCHANGE = env("RENDERED_BOARDS_EXCHANGE")
    MESSAGES_EXCHANGE = env("MESSAGES_EXCHANGE")
    LOGGER_FORMAT_DEBUG = env("LOGGER_FORMAT_DEBUG", None)
    LOGGER_FORMAT_INFO = env("LOGGER_FORMAT_INFO", None)
    REDIS_TOPIC_NAME = env("REDIS_TOPIC_NAME")
    REDIS_URL = env("REDIS_URL")
    INSTANCE_ID = env("INSTANCE_ID")
